apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: customnginx
  name: customnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: customnginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: customnginx
    spec:
      containers:
      - image: praqma/network-multitool:extra
        name: network-multitool
        resources: {}
status: {}
