apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: multitool
  name: multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitool
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: multitool
    spec:
      containers:
      - image: praqma/network-multitool:extra
        name: network-multitool
        resources: {}
status: {}
