apiVersion: apps/v1
kind: Deployment
metadata:
  name: envtest
spec:
  selector:
    matchLabels:
      name: envtest
  replicas: 1
  template:
    metadata:
      labels:
        name: envtest
    spec:
      containers:
      - name: envtest
        image: praqma/secrets-demo
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: LANGUAGE
          valueFrom:
            configMapKeyRef:
              name: envtest
              key: language
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: envtest
              key: api-key
        resources: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envtest
data:
  language: English
---
apiVersion: v1
kind: Secret
metadata:
  name: envtest
type: Opaque
data:
  api-key: c3VwZXJTZWNyZXRWYWx1ZVdoaWNoSXNCYXNlNjRFbmNvZGVkCg==
